"""
Django settings for admincu project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c5!2z8em#djn1n^e-04t8*vk_*%bucnyi0z_-qjfangd5c-6-='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.humanize',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_afip',
    'django_mercadopago',
    'django_filters',
    'termsandconditions',
    'import_export',
    'maintenance_mode',
    'anymail',
    'mailer',
    'formtools',
    'django_crontab',
    'consorcios',
    'arquitectura',
    'creditos',
    'comprobantes',
    'op',
    'contabilidad',
    'reportes',
    'socio',
    'perfil',
    'biblioteca',
    'resumenes',
    'herramientas',
    'expensas_pagas',
    'rest_framework',
    'api',
    'simple_solutions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'termsandconditions.middleware.TermsAndConditionsRedirectMiddleware',
    'admincu.request_exposer.RequestExposerMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware'
]

ROOT_URLCONF = 'admincu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'admincu.funciones.context_consorcio',
            ],
        },
    },
]

WSGI_APPLICATION = 'admincu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'adminmut',
        'USER': 'root',
        'PASSWORD': 'Arnold21.',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Salta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    )

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media")

# Redireccion cuando el login no es correcto.
LOGIN_URL = '/login/'

# Redireccion cuando el login es correcto.
LOGIN_REDIRECT_URL = "/"

# Redireccion cuando el logout es correcto.
LOGOUT_REDIRECT_URL = '/login/'

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

# Configuracion de MercadoPago
MERCADOPAGO = {
	'autoprocess': True,
	'success_url': 'mp-success',
	'failure_url': 'mp-failed',
	'pending_url': 'mp-pending',
	'base_host': 'https://www.admincu.com'
}

# Configuracion de Terminos y Condiciones
# ACCEPT_TERMS_PATH = 'terms/accept/'
TERMS_EXCLUDE_URL_PREFIX_LIST = ['/admincudj/', '/logout/', '/recuperar-pass/']
TERMS_BASE_TEMPLATE = 'termsandconditions/terminosycondiciones.html'

# Configuracion de mail para recuperacion de password
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = "mailer.backend.DbBackend"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
#EMAIL_HOST_USER = ''
#EMAIL_HOST_PASSWORD = ''
#EMAIL_USE_TLS = False
MAILER_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#MAILER_EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
DEFAULT_FROM_EMAIL = 'Equipo de AdminCU <no-reply@admincu.com>'

#ANYMAIL = {
#    # (exact settings here depend on your ESP...)
#    "MAILGUN_API_KEY": "key-84be4eea06e19ea870cff9f01f2b65fb",
#    "MAILGUN_SENDER_DOMAIN": 'admincu.com',
#}

# Email con plantillas
TEMPLATED_EMAIL_BACKEND = 'templated_email.backends.vanilla_django.TemplateBackend'

# Maintenance mode
MAINTENANCE_MODE_TEMPLATE = 'mantenimiento.html'
MAINTENANCE_MODE_IGNORE_URLS = ('/logout/', '/login/', '/front/', '/admindepdj/')
MAINTENANCE_MODE_IGNORE_STAFF = True

# # Configuraciones de seguridad
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240
# SECURE_HSTS_SECONDS = 3600 # Cambiar a 31536000 el 20/05/2018
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# X_FRAME_OPTIONS = 'DENY'


CRONJOBS = [
#    ('* * * * * TZ=America/Argentina/Salta', 'herramientas.cron.send_mail'),
#    ('0,20,40 * * * * TZ=America/Argentina/Salta', 'herramientas.cron.retry_deferred'),
#    ('0 0 * * * TZ=America/Argentina/Salta', 'herramientas.cron.purge_mail_log'),
    ('*/20 * * * * TZ=America/Argentina/Salta', 'creditos.cron.procesar_liquidaciones'),
    ('0 */2 * * * TZ=America/Argentina/Salta', 'creditos.cron.enviar_mails_facturas'),
    ('30 23 * * * TZ=America/Argentina/Salta', 'comprobantes.cron.hacer_asiento'),
    ('0 * * * * TZ=America/Argentina/Salta', 'comprobantes.cron.chequear_mp'),
    ('0 22 * * * TZ=America/Argentina/Salta', 'reportes.cron.enviar_mails_cierres'),
    ('0 10 * * * TZ=America/Argentina/Salta', 'expensas_pagas.cron.procesar_expenas_pagas'),
    ('0 23 * * * TZ=America/Argentina/Salta', 'simple_solutions.cron.procesar_simple_solutions'),
    ('0 * * * * TZ=America/Argentina/Salta', 'comprobantes.cron.procesar_recibos_masivos'),
]
